//
//  StringConstant.swift
//  Lumi
//
//  Created by Rishabh Sharma on 06/04/22.
//

import Foundation
import UIKit

enum StringConstant : String {
    case cancel = "Cancel"
    case done = "Done"
    case ok = "Ok"
    case remove = "Remove"
    case custom = "custom"
    case error = "error"
    case sent = "Sent"
    enum WelcomeScreen {
        static let quote1 = "Real connections happen face to face in real life"
        static let quote2 = "A dream you dream alone is only a dream"
        static let quote3 = "You may say I'm a dreamer, but I'm not"
        static let quote4 = "Love is not something we give or get"
        static let quote5 = "More people you meet more you get to know."
        static let bottomScreenTextView = "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Terms & Conditions"
        static let termsAndCondition = "Terms & Conditions"
        static let continueWithFacebook = "Can not connect with Facebook,try again "
        static let continueWithInstagram = "Can not connect with Instagram,try again "
        static let invalidPhoneNo = "Phone number is invalid"
        static let phoneNoEmpty = "Phone Number field is empty."
        static let invalidTextField = "Text field is empty"
        static let otpCheck = "Invalid OTP,try again"
        static let otpEmpty = "Otp field is empty."
        static let emptyString = ""
        static let font = "Gill Sans"
        static let fontBold = "GillSans-Bold"
        static let fontSemibold = "GillSans-SemiBold"
    }
    enum SignUp {
        static let nameInvalid = "Name is either empty or not valid"
        static let photosInvalid = "Please add atleast three images"
        static let dobInvalid =  "Date of Birth is empty"
        static let otpEmpty = "Otp field is empty"
        static let resendCode = "Otp has sent again"
        static let digits = "1234567890"
    }
    enum Profile {
        static let locationEmpty = "Location is empty"
        static let selectOne = "Please select one option"
        static let homeTownEmpty = "Home town is empty"
        static let homeTownInvalid = "Enter a valid home town"
        static let jobEmpty = "Job is empty."
        static let imageSelect = "Choose where you want to select image from"
        static let male = "Male"
        static let female = "Female"
        static let nonBinary = "Non-Binary"
        static let quo1 = "I’ll know I’ve met the person of my dreams when?"
        static let quo2 = "The best way to my heart is?"
        static let quo3 = "We should definitely go on a date if?"
        static let quo4 = "The key to getting to know me is?"
        static let invalidBio = "Please answer atleast 2 questions"
        static let men = "Men"
        static let women = "Women"
        static let menAndWomen = "Men + Women"
        static let genderFlucid = "Gender Fluid People"
        static let highSchool = "High School"
        static let undergraduate = "Undergraduate"
        static let postGraduate = "Post Graduate"
        static let preferNotToSay =  "Prefer not to say"
        static let buddhism = "Buddhism"
        static let christianity = "Christianity"
        static let judaism = "Judaism"
        static let islam = "Islam"
        static let hinduism = "Hinduism"
        static let other = "Other"
        static let none = "None"
        static let liberal = "Liberal"
        static let moderate = "Moderate"
        static let conservative = "Conservative"
        static let yes = "Yes"
        static let no = "No"
        static let sometimes = "Sometimes"
        static let photoLibrary = "Photo Library"
        static let dateFormate = "MM/dd/yyyy"
        static let dateFormateWithTime = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        static let locale = "en_US_POSIX"
        static let timeZone = "IST"
    }
    enum Home {
        static let booked = "Booked"
        static let yourLocation = "Your Location"
        static let event = "Event"
        static let lumiTutorial = "lumiTutorial"
        static let mp4 = "mp4"
        static let cardNameInvalid = "Enter Complete Name"
        static let cardNoInvalid = "Enter Correct Card Number"
        static let monthInvalid = "Enter Month Expiration"
        static let yearInvalid = "Enter Month Year"
        static let cvvInvalid = "Enter CVV"
        static let selectMonth = "Select a Month"
        static let selectYear = "Select a Year"
        static let inappropriateContent = "Inappropriate Content"
        static let hatespeechorvoilence = "Hate speech or voilence"
        static let idontwantthemtoseeme = "I don't want them to see me"
        static let others = "Others"
        static let reportSubmitted = "Report Submitted"
        static let offerToBuy = "Offer to buy"
        static let ticket = "'s ticket"
        static let sureInvite = "Are you sure you want to Invite"
        static let thisEvent = "to this event?"
        static let check = "Please check the option"
        static let invite = "Invite"
        static let toanEvent = "to an event"
        static let height = "Height:"
        static let birthDay = "BirthDay:"
        static let education = "Education:"
        static let job = "Job"
        static let religiousBelief = "Religious Belief:"
        static let politicalLeaning = "Political Leaning:"
        static let cigarette = "Cigarette:"
        static let marijuana = "Marijuana"
        static let drugs = "Drugs:"
        static let homeTown = "Home Town:"
        static let age = "Age:"
        static let intrestedin = "Intrested In:"
        static let alcohol = "Alcohol:"
    }
    enum Menu {
        static let updatePhone = "Update Phone Number"
        static let updateNumberStatus = "updateNumberStatus"
        static let pending = "PENDING"
        static let buyTicket = "Buy Ticket"
        static let unreveal = "Unreveal"
        static let bookingsRevealed = "Bookings Revealed"
        static let bookingID = "Booking ID"
        static let selfUser = "self"
        static let others = "others"
        static let basicInfo = "Basic Info"
        static let bio = "Bio"
        static let workEducation = "Work & Education"
        static let preference = "Preference"
        static let gender = "Gender"
        static let zodiac = "Zodiac"
        static let height = "Height"
        static let religiousBelief = "Religious Belief"
        static let politicalLeaning = "Political Leaning"
        static let cigarette = "Cigarette"
        static let marijuana = "Marijuana"
        static let drugs = "Drugs"
        static let homeTown = "Home Town"
        static let age = "Age"
        static let intrestedin = "Intrested In"
        static let alcohol = "Alcohol"
        static let work = "Work"
        static let education = "Education"        
    }
    enum ViewController {
        static let lmWelcomeScreenVC = "LMWelcomeScreenVC"
        static let lmTermsAndConditionVC = "LMTermsAndConditionVC"
        static let lmPageVC = "LMPageVC"
        static let lmPhoneNoVM = "LMPhoneNoVM"
        static let lmOtpVM = "LMOtpVM"
        static let lmCountryCodeTC = "LMCountryCodeTC"
        static let lmContinueWithPhoneNoVC = "LMContinueWithPhoneNoVC"
        static let lmCountryCodeSelectVC = "LMCountryCodeSelectVC"
        static let lmSignupOTPVC = "LMSignupOTPVC"
        static let lmCreateNewAccountVC = "LMCreateNewAccountVC"
        static let lmCreateAccountPopupVC = "LMCreateAccountPopupVC"
        static let lmUserProfileVC = "LMUserProfileVC"
        static let lmProfileVC = "LMProfileVC"
        static let lmUserHeightVC = "LMUserHeightVC"
        static let lmUserIntrestedVC = "LMUserIntrestedVC"
        static let main = "Main"
        static let preLogin = "PreLogin"
        static let countryInfo = "CountryInfo"
        static let cityInfo = "CityInfo"
        static let lmUserIntrestAgeVC = "LMUserIntrestAgeVC"
        static let lmUserLocationVC = "LMUserLocationVC"
        static let entity = "Entity"
        static let lmUserHomeTownVC = "LMUserHomeTownVC"
        static let lmUserJobVC = "LMUserJobVC"
        static let lmUserEducationVC = "LMUserEducationVC"
        static let lmUserReligionVC = "LMUserReligionVC"
        static let lmUserPoliticalVC = "LMUserPoliticalVC"
        static let lmUserCigarettesVC = "LMUserCigarettesVC"
        static let lmUserAlcoholVC = "LMUserAlcoholVC"
        static let lmUserMarijuanaVC = "LMUserMarijuanaVC"
        static let lmUserDrugsVC = "LMUserDrugsVC"
        static let lmHomeMapVC = "LMHomeMapVC"
        static let lmEventsCardsCC = "LMEventsCardsCC"
        static let lmEventsPageVC = "LMEventsPageVC"
        static let lmBioTC = "LMBioTC"
        static let city = "city"
        static let lmEventsImageCC = "LMEventsImageCC"
        static let header = "header"
        static let home = "Home"
        static let lmSavedCardsTC = "LMSavedCardsTC"
        static let lmMatchesImagesCC = "LMMatchesImagesCC"
        static let lmMaybeMatchesTC = "LMMaybeMatchesTC"
        static let lmUserBioCC = "LMUserBioCC"
        static let lmInviteEventTC = "LMInviteEventTC"
        static let lmSubscriptionVC = "LMSubscriptionVC"
        static let lmSubscriptionPageVC = "LMSubscriptionPageVC"
        static let lmLumidatesTC = "LMLumidatesTC"
        static let lmSettingsTC = "LMSettingsTC"
        static let menu = "Menu"
        static let profile = "MyProfile"
        static let lmUpdatePhoneVC = "LMUpdatePhoneVC"
        static let lmLumidatesImagesCC = "LMLumidatesImagesCC"
        static let lmInvitesSentVC = "LMInvitesSentVC"
        static let lmInvitesSentTC = "LMInvitesSentTC"
        static let lmInvitesReceivedVC = "LMInvitesReceivedVC"
        static let lmInvitesReceivedTC = "LMInvitesReceivedTC"
        static let lmMyBookingsTC = "LMMyBookingsTC"
        static let lmRevealEventsTC = "LMRevealEventsTC"
        static let lmChatTC = "LMChatTC"
        static let lmNamePhotosTC = "LMNamePhotosTC"
        static let lmBasicInfoTC = "LMBasicInfoTC"
        static let lmMyBioTC = "LMMyBioTC"
        static let lmWorkEducationTC = "LMWorkEducationTC"
        static let lmPreferenceTC = "LMPreferenceTC"
        static let lmMyProfileCellTC = "LMMyProfileCellTC"
        static let lmMyBioQuesTC = "LMMyBioQuesTC"
        static let footerCell = "FooterCell"
        static let lmMyPhotosCC = "LMMyPhotosCC"
        static let lmViewAsTC = "LMViewAsTC"
        static let lmViewImagesCC = "LMViewImagesCC"
        static let lmShowPhotosCC = "LMShowPhotosCC"
        static let lmUpdateBioTC = "LMUpdateBioTC"
    }
    enum Constants {
        static let loginDone = "Login Done"
        static let token = "token"
        static let status = "status"
        static let subscriptionStatus = "subscription"
    }
    enum RegEx {
        static let phoneNoRegex = "^[0-9+]{0,1}+[0-9]{9,10}$"
        static let alphabets = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz "
    }
}
